Output "docs/vhs/exec.gif"

Set Shell "bash"
Set FontSize 16
Set Width 1200
Set Height 700
Set Theme "Catppuccin Mocha"
Set TypingSpeed 75ms

Type "unset TMUX"
Enter
Sleep 500ms

Type "./duck"
Enter
Sleep 2s

Type "j"
Sleep 500ms
Type "j"
Sleep 500ms
Type "j"
Sleep 2s

Type "e"
Sleep 1500ms

Type "hostname"
Enter
Sleep 1s

Type "ls /"
Enter
Sleep 1s

Type "exit"
Enter
Sleep 1500ms

Sleep 1s

Type "q"
Sleep 1s
